name: auth_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  loading_animation_widget: ^1.2.0+2
  responsive_sizer: ^3.0.8
  cached_network_image: ^3.2.1
  skeletons: ^0.0.3
  page_transition: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  build_runner: ^2.1.11
  hive_generator: ^1.1.3

flutter:
  fonts:
    - family: Avenir
      fonts:
        - asset: "assets/fonts/Avenir-Medium.ttf"
        - asset: "assets/fonts/Avenir-Heavy.ttf"
          weight: 700
        - asset: "assets/fonts/Avenir-Black.ttf"
          weight: 900 
  uses-material-design: true
