name: clean_news
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  responsive_sizer: ^3.1.1
  bloc: ^8.1.0
  freezed: ^2.2.0
  auto_route: ^5.0.2
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.3
  http: ^0.13.5
  loading_animation_widget: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: "assets/fonts/Poppins-Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Poppins-ExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/Poppins-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Poppins-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Poppins-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Poppins-Semibold.ttf"
          weight: 600 
        - asset: "assets/fonts/Poppins-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Poppins-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Poppins-Black.ttf"
          weight: 900
